Repository openshift/ceph-csi, pull requests merged in 2021-06, with the labels that each got.

#52 BUG 1961647: Continue thick-provisioning of RBD images on CreateVolume restart
  internal/rbd/controllerserver.go
  internal/rbd/controllerserver_test.go
  internal/rbd/rbd_util.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#55 Bug 1969427: util: returns actual error instead of ErrPoolNotFound
  internal/util/cephcmds.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#57 sync devel with master branch
  .github/workflows/publish-artifacts.yaml
  build.env
  docs/static-pvc.md
  e2e/rbd.go
  e2e/rbd_helper.go
  internal/rbd/rbd_util.go
  scripts/minikube.sh
Labels: approved, lgtm

#58 BUG 1973046: rbd: fail fast in create volume for mismatch encryption
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#60 BUG 1973271: rbd: add validation for thick restore/clone
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#59 sync devel with master branch
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/utils.go
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
  internal/rbd/controllerserver_test.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_util.go
Labels: approved, lgtm

#61 BUG 1974816: util: allow any KMS connection to be configured by ConfigMap
  examples/kms/vault/csi-kms-connection-details.yaml
  examples/kms/vault/csi-vaulttokenreview-rbac.yaml
  examples/kms/vault/vault.yaml
  internal/util/vault_tokens.go
  internal/util/vault_tokens_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
